### ISSUE TITLE
its super laggy in the config

### ISSUE THREAD

**Issue by Jenssons** [HipsterSloth/PSMoveSteamVRBridge#10]
when i try to do the set up it lags like on the magnetometer calibration

**Comment by zelmon64** [comment]
@Jenssons This sort of problem should first be asked in the [PSMoveService google group](https://groups.google.com/forum/#!forum/psmoveservice) then if a real problem with the code gets identified a detailed issue can be made.

This sounds like PSMoveService is probably lagging because the frame rate of your cameras is set too high. If lowering the frame rate doesn't fix this please make a thread on the google group. 

I'll close this for now.
